<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link href='http://fonts.googleapis.com/css?family=Creepster|Audiowide' rel='stylesheet' type='text/css'>
    <link href="/resources/css/404.css" rel="stylesheet">
    <title>Error</title>
</head>
<body>

<p class="error-code">
    404
</p>

<p class="not-found">Not<br/>Found</p>

<div class="clear"></div>
<div class="content">
    The page your are looking for is not found.
    <br/><a href="/">Go Home</a><br/>
</div>

<div style="display: none">
        <pre>
        <?php echo $code;?><br/>
            <?php var_dump($msg);?>
        </pre>
</div>
</body>
</html>
