<?php require_once VIEW_PATH . "/common/header.phtml"; ?>

<?php require_once VIEW_PATH . "/common/topbar.phtml"; ?>
    <div class="container-fluid">
    <div class="row-fluid">
<?php require_once VIEW_PATH . "/common/leftMenu.phtml"; ?>


    <noscript>
        <div class="alert alert-block span10">
            <h4 class="alert-heading">Warning!</h4>

            <p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled
                to use this site.</p>
        </div>
    </noscript>

    <div id="content" class="span10">
    <!-- content starts -->


    <div>
        <ul class="breadcrumb">
            <li>
                <a href="#">Home</a> <span class="divider">/</span>
            </li>
            <li>
                <a href="#">Dashboard</a>
            </li>
        </ul>
    </div>

    <div class="row-fluid">
        <div class="box span12">
            <div class="box-header well">
                <h2><i class="icon-info-sign"></i> Introduction</h2>

                <div class="box-icon">
                    <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <h1>Yaf.Scaffold
                    <small>免费、开源的脚手架工具.</small>
                </h1>
                <p>在一次项目中，使用Yaf与Charisma搭建的脚手架工具，用于快速搭建项目的管理后台。现在向您分享了它，希望能为您的工作带来帮助。</p>

                <p><b>当然，欢迎对这个项目感兴趣的童鞋，也加入这个项目！</b></p>

                <p class="center">
                    <a href="https://github.com/Neeke/Yaf.Scaffold" target="_blank" class="btn btn-large"><i
                            class="icon-download-alt"></i> Github</a>
                </p>

                <div class="clearfix"></div>
            </div>
        </div>
    </div>

    <div class="row-fluid sortable">

        <div class="box span4">
            <div class="box-header well" data-original-title>
                <h2><i class="icon-user"></i> Contributors</h2>

                <div class="box-icon">
                    <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                    <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
                </div>
            </div>
            <div class="box-content">
                <div class="box-content">
                    <ul class="dashboard-list">
                        <li>
                            <a href="#">
                                <img class="dashboard-avatar" alt="Neeke"
                                     src="<?php echo helper_common::avatar('ciogao@gmail.com', 50); ?>"></a>
                            <strong>Name:</strong>
                            <a href="https://github.com/Neeke" target="_blank">Neeke</a><br>
                            <strong>Since:</strong> 18/08/2013<br>
                            <strong>Status:</strong> <span class="label label-success">Owner</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div><!--/span-->

    </div><!--/row-->

<?php require_once VIEW_PATH . '/common/footer.phtml'; ?>