<script src="/resources/js/jquery-1.7.2.min.js"></script>
<script src="/resources/js/jquery-ui-1.8.21.custom.min.js"></script>
<script src="/resources/js/bootstrap-transition.js"></script>
<script src="/resources/js/bootstrap-alert.js"></script>
<script src="/resources/js/bootstrap-modal.js"></script>
<script src="/resources/js/bootstrap-dropdown.js"></script>
<script src="/resources/js/bootstrap-scrollspy.js"></script>
<script src="/resources/js/bootstrap-tab.js"></script>
<script src="/resources/js/bootstrap-tooltip.js"></script>
<script src="/resources/js/bootstrap-popover.js"></script>
<script src="/resources/js/bootstrap-button.js"></script>
<!-- accordion library (optional, not used in demo) -->
<script src="/resources/js/bootstrap-collapse.js"></script>
<!-- carousel slideshow library (optional, not used in demo) -->
<script src="/resources/js/bootstrap-carousel.js"></script>
<!-- autocomplete library -->
<script src="/resources/js/bootstrap-typeahead.js"></script>
<!-- tour library -->
<script src="/resources/js/bootstrap-tour.js"></script>
<!-- library for cookie management -->
<script src="/resources/js/jquery.cookie.js"></script>
<!-- calander plugin -->
<script src='/resources/js/fullcalendar.min.js'></script>
<!-- data table plugin -->
<script src='/resources/js/jquery.dataTables.min.js'></script>

<!-- chart libraries start -->
<script src="/resources/js/excanvas.js"></script>
<script src="/resources/js/jquery.flot.min.js"></script>
<script src="/resources/js/jquery.flot.pie.min.js"></script>
<script src="/resources/js/jquery.flot.stack.js"></script>
<script src="/resources/js/jquery.flot.resize.min.js"></script>
<!-- chart libraries end -->

<!-- select or dropdown enhancer -->
<script src="/resources/js/jquery.chosen.min.js"></script>
<!-- checkbox, radio, and file input styler -->
<script src="/resources/js/jquery.uniform.min.js"></script>
<!-- plugin for gallery image view -->
<script src="/resources/js/jquery.colorbox.min.js"></script>
<!-- rich text editor library -->
<script src="/resources/js/jquery.cleditor.min.js"></script>
<!-- notification plugin -->
<script src="/resources/js/jquery.noty.js"></script>
<!-- file manager library -->
<script src="/resources/js/jquery.elfinder.min.js"></script>
<!-- star rating plugin -->
<script src="/resources/js/jquery.raty.min.js"></script>
<!-- for iOS style toggle switch -->
<script src="/resources/js/jquery.iphone.toggle.js"></script>
<!-- autogrowing textarea plugin -->
<script src="/resources/js/jquery.autogrow-textarea.js"></script>
<!-- multiple file upload plugin -->
<script src="/resources/js/jquery.uploadify-3.1.min.js"></script>
<!-- history.js for cross-browser state change on ajax -->
<script src="/resources/js/jquery.history.js"></script>
<!-- application script for Charisma demo -->
<script src="/resources/js/charisma.js"></script>
</body>
</html>