<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Welcome to Yaf.Scaffold</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Charisma, a fully featured, responsive, HTML5, Bootstrap admin template.">
    <meta name="author" content="Muhammad Usman">

    <!-- The styles -->
    <link id="bs-css" href="/resources/css/bootstrap-cerulean.css" rel="stylesheet">
    <style type="text/css">
        body {
            padding-bottom: 40px;
        }

        .sidebar-nav {
            padding: 9px 0;
        }
    </style>
    <link href="/resources/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/resources/css/charisma-app.css" rel="stylesheet">
    <link href="/resources/css/jquery-ui-1.8.21.custom.css" rel="stylesheet">
    <link href='/resources/css/fullcalendar.css' rel='stylesheet'>
    <link href='/resources/css/fullcalendar.print.css' rel='stylesheet' media='print'>
    <link href='/resources/css/chosen.css' rel='stylesheet'>
    <link href='/resources/css/uniform.default.css' rel='stylesheet'>
    <link href='/resources/css/colorbox.css' rel='stylesheet'>
    <link href='/resources/css/jquery.cleditor.css' rel='stylesheet'>
    <link href='/resources/css/jquery.noty.css' rel='stylesheet'>
    <link href='/resources/css/noty_theme_default.css' rel='stylesheet'>
    <link href='/resources/css/elfinder.min.css' rel='stylesheet'>
    <link href='/resources/css/elfinder.theme.css' rel='stylesheet'>
    <link href='/resources/css/jquery.iphone.toggle.css' rel='stylesheet'>
    <link href='/resources/css/opa-icons.css' rel='stylesheet'>
    <link href='/resources/css/uploadify.css' rel='stylesheet'>

    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- The fav icon -->
    <link rel="shortcut icon" href="/resources/img/favicon.ico">

</head>

<body>

<script>
    var $CONFIG =
    <?php if (isset($config) && is_array($config) && count($config) > 0){
           echo json_encode($config);
           }else{
               echo '{}';
           } ?>
</script>