<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Welcome to Yaf.Scaffold</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Charisma, a fully featured, responsive, HTML5, Bootstrap admin template.">
    <meta name="author" content="Muhammad Usman">

    <!-- The styles -->
    <link id="bs-css" href="/resources/css/bootstrap-cerulean.css" rel="stylesheet">
    <style type="text/css">
        body {
            padding-bottom: 40px;
        }

        .sidebar-nav {
            padding: 9px 0;
        }
    </style>
    <link href="/resources/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="/resources/css/charisma-app.css" rel="stylesheet">
    <link href="/resources/css/jquery-ui-1.8.21.custom.css" rel="stylesheet">
    <link href='/resources/css/fullcalendar.css' rel='stylesheet'>
    <link href='/resources/css/fullcalendar.print.css' rel='stylesheet' media='print'>
    <link href='/resources/css/chosen.css' rel='stylesheet'>
    <link href='/resources/css/uniform.default.css' rel='stylesheet'>
    <link href='/resources/css/colorbox.css' rel='stylesheet'>
    <link href='/resources/css/jquery.cleditor.css' rel='stylesheet'>
    <link href='/resources/css/jquery.noty.css' rel='stylesheet'>
    <link href='/resources/css/noty_theme_default.css' rel='stylesheet'>
    <link href='/resources/css/elfinder.min.css' rel='stylesheet'>
    <link href='/resources/css/elfinder.theme.css' rel='stylesheet'>
    <link href='/resources/css/jquery.iphone.toggle.css' rel='stylesheet'>
    <link href='/resources/css/opa-icons.css' rel='stylesheet'>
    <link href='/resources/css/uploadify.css' rel='stylesheet'>

    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- The fav icon -->
    <link rel="shortcut icon" href="/resources/img/favicon.ico">

</head>

<body>
<div class="container-fluid">
    <div class="row-fluid">

        <div class="row-fluid">
            <div class="span12 center login-header">
                <h2>Welcome to Yaf.Scaffold</h2>
            </div>
            <!--/span-->
        </div>
        <!--/row-->

        <div class="row-fluid">
            <div class="well span5 center login-box">
                <div class="alert alert-info">
                    Please login with your Username and Password.
                </div>
                <form class="form-horizontal" action="?" method="post">
                    <fieldset>
                        <div class="input-prepend" title="Username" data-rel="tooltip">
                            <span class="add-on"><i class="icon-user"></i></span>
                            <input autofocus class="input-large span10" name="username" id="username" type="text" value=""/>
                        </div>
                        <div class="clearfix"></div>

                        <div class="input-prepend" title="Password" data-rel="tooltip">
                            <span class="add-on"><i class="icon-lock"></i></span>
                            <input class="input-large span10" name="password" id="password" type="password" value=""/>
                        </div>
                        <div class="clearfix"></div>

                        <div class="input-prepend">
                            <label class="remember" for="remember"><input type="checkbox" id="remember"/>Remember
                                me</label>
                        </div>
                        <div class="clearfix"></div>

                        <p class="center span5">
                            <button type="submit" class="btn btn-primary">Login</button>
                        </p>
                    </fieldset>
                </form>
            </div>
            <!--/span-->
        </div>
        <!--/row-->
    </div>
    <!--/fluid-row-->

</div>
<!--/.fluid-container-->

<script src="/resources/js/jquery-1.7.2.min.js"></script>
<script src="/resources/js/jquery-ui-1.8.21.custom.min.js"></script>
<script src="/resources/js/bootstrap-transition.js"></script>
<script src="/resources/js/bootstrap-alert.js"></script>
<script src="/resources/js/bootstrap-modal.js"></script>
<script src="/resources/js/bootstrap-dropdown.js"></script>
<script src="/resources/js/bootstrap-scrollspy.js"></script>
<script src="/resources/js/bootstrap-tab.js"></script>
<script src="/resources/js/bootstrap-tooltip.js"></script>
<script src="/resources/js/bootstrap-popover.js"></script>
<script src="/resources/js/bootstrap-button.js"></script>
<!-- accordion library (optional, not used in demo) -->
<script src="/resources/js/bootstrap-collapse.js"></script>
<!-- carousel slideshow library (optional, not used in demo) -->
<script src="/resources/js/bootstrap-carousel.js"></script>
<!-- autocomplete library -->
<script src="/resources/js/bootstrap-typeahead.js"></script>
<!-- tour library -->
<script src="/resources/js/bootstrap-tour.js"></script>
<!-- library for cookie management -->
<script src="/resources/js/jquery.cookie.js"></script>
<!-- calander plugin -->
<script src='/resources/js/fullcalendar.min.js'></script>
<!-- data table plugin -->
<script src='/resources/js/jquery.dataTables.min.js'></script>

<!-- chart libraries start -->
<script src="/resources/js/excanvas.js"></script>
<script src="/resources/js/jquery.flot.min.js"></script>
<script src="/resources/js/jquery.flot.pie.min.js"></script>
<script src="/resources/js/jquery.flot.stack.js"></script>
<script src="/resources/js/jquery.flot.resize.min.js"></script>
<!-- chart libraries end -->

<!-- select or dropdown enhancer -->
<script src="/resources/js/jquery.chosen.min.js"></script>
<!-- checkbox, radio, and file input styler -->
<script src="/resources/js/jquery.uniform.min.js"></script>
<!-- plugin for gallery image view -->
<script src="/resources/js/jquery.colorbox.min.js"></script>
<!-- rich text editor library -->
<script src="/resources/js/jquery.cleditor.min.js"></script>
<!-- notification plugin -->
<script src="/resources/js/jquery.noty.js"></script>
<!-- file manager library -->
<script src="/resources/js/jquery.elfinder.min.js"></script>
<!-- star rating plugin -->
<script src="/resources/js/jquery.raty.min.js"></script>
<!-- for iOS style toggle switch -->
<script src="/resources/js/jquery.iphone.toggle.js"></script>
<!-- autogrowing textarea plugin -->
<script src="/resources/js/jquery.autogrow-textarea.js"></script>
<!-- multiple file upload plugin -->
<script src="/resources/js/jquery.uploadify-3.1.min.js"></script>
<!-- history.js for cross-browser state change on ajax -->
<script src="/resources/js/jquery.history.js"></script>
<!-- application script for Charisma demo -->
<script src="/resources/js/charisma.js"></script>
</body>
</html>
