<div class="modal hide fade" id="scaffoldEdit">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Edit</h3>
    </div>
    <div class="modal-body">
        <form class="form-horizontal" id="form-modify">
            <div class="box-content">
                <div class="control-group">
                    <?php foreach($columns as $column_name => $info){?>
                        <label class="control-label"><?php echo $column_name;?> [<?php echo $info['COLUMN_COMMENT'];?>]</label>
                        <div class="controls">
                            <input class="input-xlarge focused" id="focusedInput" type="text" name="<?php echo $column_name;?>" value="">
                        </div>
                        <br />
                    <?php }?>
                </div>
            </div>
        </form>

    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Close</a>
        <a href="#" class="btn btn-primary btn-modify">Save changes</a>
    </div>
</div>