<?php require_once VIEW_PATH."/common/header.phtml";?>

<?php require_once VIEW_PATH."/common/topbar.phtml";?>
<div class="container-fluid">
<div class="row-fluid">
<?php require_once VIEW_PATH."/common/leftMenu.phtml";?>

    <div id="content" class="span10">
    <!-- content starts -->

<div class="row-fluid sortable">
<div class="box span12">
<div class="box-header well" data-original-title>
    <h2><i class="icon-user"></i> <?php echo $tableName;?></h2>
    <div class="box-icon">
        <a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
        <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
        <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
    </div>
</div>
<div class="box-content">
    <span id="api-getrow" data-api="/admin/getrow"></span>
    <span id="api-modify" data-api="/admin/modify"></span>
    <span id="api-remove" data-api="/admin/remove"></span>
<table class="table table-striped table-bordered bootstrap-datatable datatable">
<thead>
<tr>
    <?php
    foreach($columns as $column_name => $info){
    ?>
        <th><?php echo $column_name;?></th>
    <?php }?>
    <th>Actions</th>
</tr>
</thead>
<tbody>
<?php foreach ($data as $info) {?>
    <tr>
    <?php foreach($columns as $column_name => $_info){?>
        <td><?php echo $info[$column_name];?></td>
    <?php }?>
        <td class="center" data-primary-value="<?php echo $info['user_id'];?>">
            <a class="btn btn-success btn-view" href="javascript:;"><i class="icon-zoom-in icon-white"></i>View</a>
            <a class="btn btn-info btn-edit" href="javascript:;"><i class="icon-edit icon-white"></i>Edit</a>
            <a class="btn btn-danger btn-remove" href="javascript:;"><i class="icon-trash icon-white"></i>Delete</a>
        </td>
    </tr>
<?php }?>
</tbody>
</table>
</div>
</div><!--/span-->

</div><!--/row-->
</div>

<?php require_once VIEW_PATH.'/scaffoldView/modify.phtml';?>


<?php require_once VIEW_PATH.'/common/footer.phtml';?>